"""Domain models, FSM, policies, and ports for DZTGBot.

``DraftState`` is owned by ``domain.fsm`` and re-exported here so importers use
one canonical lifecycle enum (not a reduced models-local copy).
"""

from .callbacks import (
    CALLBACK_VERSION,
    CallbackAction,
    CallbackAuthorizationInput,
    CallbackParseError,
    CallbackTokenRecord,
    ParsedCallback,
    build_token_record,
    encode_callback_data,
    generate_opaque_token,
    hash_opaque_token,
    parse_callback_data,
)
from .errors import (
    ClassifiedOperationError,
    DomainError,
    ErrorClassification,
    ErrorKind,
    InvalidStateTransitionError,
    MutationCertainty,
    Operation,
    Retryability,
    RevisionConflictError,
    SafeErrorCode,
    StateConflictError,
    classify_definite_mutation_failure,
    classify_unknown_mutation_outcome,
)
from .fsm import (
    EXPIRABLE_STATES,
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    UNKNOWN_OUTCOME_STATES,
    DraftState,
    TransitionCommand,
    TransitionResult,
    allowed_targets,
    evaluate_transition,
    is_expirable,
    is_transition_allowed,
    requires_reconciliation,
    validate_transition,
)
from .models import (
    Attachment,
    Draft,
    JiraTaskTemplate,
    MediaKind,
    PublishedIssue,
    SourceMessageRef,
    SubmissionAttempt,
)
from .policy import (
    AUTH_CONVERSATION_TTL,
    CredentialInputKind,
    DenialCode,
    PolicyDecision,
    authorize_callback,
    classify_credential_input,
    credential_policy_decision,
    is_private_chat,
    normalize_pat_input,
    require_admin,
    require_allowed_user,
    require_private_admin,
    require_private_chat,
    user_message_for_denial,
)
from .ports import (
    AIAnalyzerPort,
    ClockPort,
    DraftRepositoryPort,
    IdGeneratorPort,
    JiraGatewayPort,
    RendererPort,
    RulesRepositoryPort,
    TaskSchedulerPort,
    UserRepositoryPort,
    VpnManagerPort,
)

__all__ = [
    # Models
    "Attachment",
    "Draft",
    "JiraTaskTemplate",
    "MediaKind",
    "PublishedIssue",
    "SourceMessageRef",
    "SubmissionAttempt",
    # FSM (canonical DraftState)
    "DraftState",
    "EXPIRABLE_STATES",
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "UNKNOWN_OUTCOME_STATES",
    "TransitionCommand",
    "TransitionResult",
    "allowed_targets",
    "evaluate_transition",
    "is_expirable",
    "is_transition_allowed",
    "requires_reconciliation",
    "validate_transition",
    # Errors
    "ClassifiedOperationError",
    "DomainError",
    "ErrorClassification",
    "ErrorKind",
    "InvalidStateTransitionError",
    "MutationCertainty",
    "Operation",
    "Retryability",
    "RevisionConflictError",
    "SafeErrorCode",
    "StateConflictError",
    "classify_definite_mutation_failure",
    "classify_unknown_mutation_outcome",
    # Callbacks
    "CALLBACK_VERSION",
    "CallbackAction",
    "CallbackAuthorizationInput",
    "CallbackParseError",
    "CallbackTokenRecord",
    "ParsedCallback",
    "build_token_record",
    "encode_callback_data",
    "generate_opaque_token",
    "hash_opaque_token",
    "parse_callback_data",
    # Policy
    "AUTH_CONVERSATION_TTL",
    "CredentialInputKind",
    "DenialCode",
    "PolicyDecision",
    "authorize_callback",
    "classify_credential_input",
    "credential_policy_decision",
    "is_private_chat",
    "normalize_pat_input",
    "require_admin",
    "require_allowed_user",
    "require_private_admin",
    "require_private_chat",
    "user_message_for_denial",
    # Ports
    "AIAnalyzerPort",
    "ClockPort",
    "DraftRepositoryPort",
    "IdGeneratorPort",
    "JiraGatewayPort",
    "RendererPort",
    "RulesRepositoryPort",
    "TaskSchedulerPort",
    "UserRepositoryPort",
    "VpnManagerPort",
]
