"""Internationalization (i18n) module for DZTGBot UI.

Supports three UI languages:
- ``zh_TW``: Taiwan Traditional Chinese (繁體中文, default)
- ``en``: English
- ``zh_CN``: China Simplified Chinese (简体中文)

Note: Issue contents (Summary & Description) automatically generated by AI intake
are ALWAYS rendered in Simplified Chinese (简体中文) regardless of the UI language.
"""

from __future__ import annotations

from enum import Enum
from typing import Dict

class Language(str, Enum):
    ZH_TW = "zh_TW"
    EN = "en"
    ZH_CN = "zh_CN"

    @classmethod
    def normalize(cls, lang: str | None) -> Language:
        if not lang:
            return cls.ZH_TW
        code = lang.strip().lower().replace("-", "_")
        if code in ("zh_tw", "zh_hk", "zh_hant", "tw", "traditional"):
            return cls.ZH_TW
        if code in ("en", "en_us", "en_gb", "english"):
            return cls.EN
        if code in ("zh_cn", "zh_sg", "zh_hans", "cn", "simplified"):
            return cls.ZH_CN
        return cls.ZH_TW


_STRINGS: Dict[str, Dict[Language, str]] = {
    # Main reply keyboard buttons
    "btn_auth": {
        Language.ZH_TW: "🔑 連結 Jira",
        Language.EN: "🔑 Link Jira",
        Language.ZH_CN: "🔑 绑定 Jira",
    },
    "btn_logout": {
        Language.ZH_TW: "🚪 Logout",
        Language.EN: "🚪 Logout",
        Language.ZH_CN: "🚪 退出登录",
    },
    "btn_my_issues": {
        Language.ZH_TW: "📋 指派給我的",
        Language.EN: "📋 Assigned to Me",
        Language.ZH_CN: "📋 指派给我的",
    },
    "btn_created_issues": {
        Language.ZH_TW: "🚩 我建的",
        Language.EN: "🚩 Created by Me",
        Language.ZH_CN: "🚩 我创建的",
    },
    "btn_search": {
        Language.ZH_TW: "🔍 搜尋",
        Language.EN: "🔍 Search",
        Language.ZH_CN: "🔍 搜索",
    },
    "btn_new": {
        Language.ZH_TW: "📝 新建",
        Language.EN: "📝 New Issue",
        Language.ZH_CN: "📝 新建工单",
    },
    "btn_standup": {
        Language.ZH_TW: "📊 站會報告",
        Language.EN: "📊 Standup Report",
        Language.ZH_CN: "📊 站会报告",
    },
    "btn_language": {
        Language.ZH_TW: "🌐 語言設置",
        Language.EN: "🌐 Language",
        Language.ZH_CN: "🌐 语言设置",
    },
    "btn_help": {
        Language.ZH_TW: "📖 說明",
        Language.EN: "📖 Help",
        Language.ZH_CN: "📖 使用说明",
    },

    # Card Actions
    "action_move": {
        Language.ZH_TW: "➡️ 移動",
        Language.EN: "➡️ Move",
        Language.ZH_CN: "➡️ 移动",
    },
    "action_edit": {
        Language.ZH_TW: "📝 編輯",
        Language.EN: "📝 Edit",
        Language.ZH_CN: "📝 编辑",
    },
    "action_comment": {
        Language.ZH_TW: "💬 留言",
        Language.EN: "💬 Comment",
        Language.ZH_CN: "💬 留言",
    },
    "action_block": {
        Language.ZH_TW: "⚠️ 阻礙",
        Language.EN: "⚠️ Block",
        Language.ZH_CN: "⚠️ 标记阻碍",
    },
    "action_assign": {
        Language.ZH_TW: "👤 指派",
        Language.EN: "👤 Assign",
        Language.ZH_CN: "👤 指派",
    },
    "action_watch": {
        Language.ZH_TW: "👁️ 關注",
        Language.EN: "👁️ Watch",
        Language.ZH_CN: "👁️ 关注",
    },
    "action_unwatch": {
        Language.ZH_TW: "👁️ 取消關注",
        Language.EN: "👁️ Unwatch",
        Language.ZH_CN: "👁️ 取消关注",
    },
    "action_subtask": {
        Language.ZH_TW: "➕ 子任務",
        Language.EN: "➕ Sub-task",
        Language.ZH_CN: "➕ 子任务",
    },
    "action_open_jira": {
        Language.ZH_TW: "在 Jira 查看 ↗",
        Language.EN: "Open in Jira ↗",
        Language.ZH_CN: "在 Jira 查看 ↗",
    },

    # Language selection messages
    "lang_select_prompt": {
        Language.ZH_TW: "🌐 <b>請選擇您的界面語言 / Select UI Language:</b>",
        Language.EN: "🌐 <b>Please select your preferred UI Language:</b>",
        Language.ZH_CN: "🌐 <b>请选择您的界面语言 / Select UI Language:</b>",
    },
    "lang_changed_notice": {
        Language.ZH_TW: "✅ 界面語言已切換為：<b>繁體中文</b>",
        Language.EN: "✅ UI language has been set to: <b>English</b>",
        Language.ZH_CN: "✅ 界面语言已切换为：<b>简体中文</b>",
    },
}


def get_text(key: str, lang: str | Language = Language.ZH_TW) -> str:
    """Resolve a localized UI string key for the target language."""
    language = Language.normalize(lang) if isinstance(lang, str) else lang
    entry = _STRINGS.get(key)
    if not entry:
        return key
    return entry.get(language, entry.get(Language.ZH_TW, key))
